### ISSUE TITLE
Commands to execute tasks

### ISSUE THREAD

**Issue by brjmoreira** [SandMT/RNA-SEQ-team#4]
@manuparra, @SandMT , @lmontosah, @DomiRojas 

¿Cómo ejecutamos los comandos para para hacer los analisis/tareas?

**Comment by SandMT** [comment]
Supongo que tenemos que "escribir los comandos" y "crear" esos contenedores/cápsulas que nos enseñaron hoy. 
El objetivo es que todo el mundo pueda reproducir nuestro análisis sin sufrimiento. 
No sé si esto se puede hacer desde el Desktop client de Git que nos hemos instalado.
No me hagas caso, me da hasta verguenza responder el hilo.
Trataré de revisar la clase a ver si pillo algo.

**Comment by manuparra** [comment]
Sí @SandMT , pero también estaría bien que indicases en el README.md esas operaciones.
No te preocupes, está todo muy bien y también que preguntes sin miedo.
En cuanto al modo de hacer el contenedor que hoy hemos visto, necesitaría que pegases el código que ejecutas para que pueda yo hacer una prueba con ello.
