### ISSUE TITLE
Crear un script que ejecute todos los comandos

### ISSUE THREAD

**Issue by jmoldon** [SandMT/RNA-SEQ-team#7]
Una cosa más que podéis hacer para rematar es crear un archivo en el repositorio que se llame `run.sh` y que contenta todos los comantos que habéis puesto en el readme. De esta manera se puede ejecutar un solo comando que lance todas las instrucciones.

Creo que esto lo podría hacer alguien de @lmontosah, @brjmoreira, @DomiRojas. ¿Qué os parece?

**Comment by brjmoreira** [comment]
Lo he intentado. No sé si era esto lo que se pretendía
Lo puedes confirmar @jmoldon
